language: go
go:
  - 1.12.x
  - 1.13.x
os:
  - linux
dist: trusty
sudo: false
install:
  # Use v1.19.1 because of this bug: https://github.com/golangci/golangci-lint/issues/840.
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.19.1
script:
  - env GO111MODULE=on golangci-lint --deadline 5m run --new-from-rev "$TRAVIS_BRANCH"
  - env GO111MODULE=on go test -v -short ./...

