language: go
go:
  - 1.12.x
  - 1.13.x
os:
  - linux
dist: trusty
sudo: false
install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.22.2
script:
  - env GO111MODULE=on golangci-lint run --new-from-rev "$TRAVIS_BRANCH" ./...
  - env GO111MODULE=on go test -v -short ./...

