name: Full Test

on:
  schedule:
    # Run every 6 hours.
    - cron: '0 */6 * * *'

jobs:
  build:
    strategy:
      matrix:
        go: [1.12, 1.13]
    name: All Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Check out
      uses: actions/checkout@v2
    - name: Test
      run: go test -v ./...
